services:
  #serviço de banco de dados, esse container vai ser usado pela API
  mastermind-mariadb:
    build:
      context: ./infra/database
    image: mastermind-mariadb
    container_name: mastermind-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "${MARIADB_HOST_PORT}:3306"
    networks:
      - mastermind

  mastermind-api:
    build:
      context: ./backend/mastermind
    image: mastermind-api
    container_name: mastermind-api
    restart: always
    environment:
      MARIADB_HOST: "mastermind-mariadb"
      MARIADB_PORT: "3306"
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_SECONDS: ${JWT_EXPIRATION_SECONDS}
    ports:
      - "${API_SWAGGER_HOST_PORT}:8080"
    networks:
      - mastermind

  mastermind-website:
    build:
      context: ./frontend/mastermind
    image: mastermind-website
    container_name: mastermind-website
    restart: always
    ports:
      - "${WEBSERVER_HOST_PORT}:80"
    networks:
      - mastermind

networks:
  mastermind:
    driver: bridge
    name: mastermind